### ISSUE TITLE
Multiple exports?

### ISSUE THREAD

**Issue by Arcanorum** [odrick/free-tex-packer-cli#1]
Any way to have multiple exports from a single ftpp config?
Such as being able to specify several groups of inputs (images/folders) and a specific outputs, so the CLI can generate several atlases with one command?

Something like:
```
{
  ...
  "projects": [ // a list of configs to use to export one after another
    {
      "inputs": {
        "images": [ "assets/characters/player01.png", "assets/characters/player02.png", ... ],
      },
      "textureName": "player",
      "output": "assets"
    },
    {
      "inputs": {
        "folders": ["assets/items"]
      },
      "textureName": "items",
      "output": "assets"
    }
  ]
  "packOptions": { ... }
}
```

as currently the only way I see of doing this is to have a different ftpp config for each separate output I want, and a separate command to run each.

**Comment by odrick** [comment]
Yes, right now only available option is a different fttp configs
