### ISSUE TITLE
Add custom exporter support for cli tool

### ISSUE THREAD

**Issue by MinchukSergei** [odrick/free-tex-packer-cli#2]
Hi. What do you think about add custom exporter like this:

```
options.exporter = {
	fileExt: argv.customext,
	template: argv.custom
}
```

and run cli command such as:
`free-tex-packer-cli --project packer.ftpp --custom [path to custom.mst file] --customext [any output extension]`

**Comment by odrick** [comment]
At the moment I don't have much time to develop this project. Feature requests are postponed.

**Comment by rainbowcreatures** [comment]
Or, simply workaround by adding your custom template into a new .mst file under node_modules\free-tex-packer-core\exporters. Also add a definition into list.json, in the same folder.

Done, you can now use your custom exporter.
